### ISSUE TITLE
Surface flux BC

### ISSUE THREAD

**Issue by yvanblanchard** [Eliasfarah0/1D-Heat-Conduction-Equation-Solver#1]
Hello,
Is it possible for you to add surface (lineic) flux as BC in your solver ?
Thank you!

**Comment by Eliasfarah0** [comment]
Hi,

Yes, adding a surface heat flux BC is possible, instead of the constant surface temperature already implemented.

A surface flux BC is also called a temperature gradient BC, so you must specify a **dT/dx** (unit: K/m) BC.
The heat flux is represented by **q = -k (dT/dx)** (unit: W/m2), based on Fourier's law of heat conduction in 1D.

Therefore the surface heat flux at the left boundary for instance can be expressed as:
**q_leftBC = - k (dT/dx)** ----> **dT/dx (at left BC) = - (q_leftBC / k)**.

Now, this temperature gradient needs to be discretized in space using a Finite difference scheme. Take for example CD scheme:
**(T_{i+1} - T_{i-1}) / (2*deltaX) = - (q_leftBC / k)**
now for node i = 1, we get in the end **T_{0} = T_{2} + (2 * deltaX * q_leftBC / k)**

Finally, this value of node 0 (**T_{0}**) needs to be added to the final discretized 1D heat conduction equation and rearranged for any of the 4 schemes listed in the solver. 

I hope this brief explanation is helpful to you.

Regards,
Elias

**Comment by yvanblanchard** [comment]
Thank you Elias
I will try to find Time to implement it.
